language: elixir

env: INFLUXDB=0.9.0-rc2 MIX_ENV=test

before_install:
  - wget -q "http://s3.amazonaws.com/influxdb/influxdb_${INFLUXDB}_amd64.deb"
  - sudo dpkg -i "influxdb_${INFLUXDB}_amd64.deb"
  - sudo service influxdb start

after_success:
  - mix coveralls.travis
