language: elixir

env: INFLUXDB=0.9.0 MIX_ENV=test

before_install:
  - wget -q "http://s3.amazonaws.com/influxdb/influxdb_${INFLUXDB}_amd64.deb"
  - sudo dpkg -i "influxdb_${INFLUXDB}_amd64.deb"
  - sudo service influxdb start

  - sleep 5
  - curl "http://localhost:8086/query?q=CREATE%20USER%20instream_test%20WITH%20PASSWORD%20%27instream_test%27%20WITH%20ALL%20PRIVILEGES"
  - sudo sed -i 's/auth-enabled = false/auth-enabled = true/' /etc/opt/influxdb/influxdb.conf

  - sleep 5
  - sudo service influxdb restart

after_success:
  - mix coveralls.travis
